Multiple Linear Regression

Multiple Linear Regression (MLR) is a supervised machine learning algorithm used to predict a continuous dependent variable using two or more independent variables.

General Equation of Multiple Linear Regression
Y=m1x1 + m2x2 + m3x3 + m4x4 + m5x5 + ..... mnxn + C

m= ((X^TX)^-1X^T)Y

Where:
Y = Dependent variable (Output)
X₁ = Study Hours
X₂ = Attendance (%)
X₃ = Assignment Score
X₄ = Internal Marks
X₅ = Practical Marks
C = Intercept
m1...m5 = Regression Coefficients

In [28]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [27]:
data=pd.read_csv("st_data.csv")
#data.count()[0]
data

    StudyHours  Attendance  Assignment  Internal  Practical  FinalMarks
0            5          75          70        68         72          71
1            6          80          72        70         75          74
2            7          82          75        74         78          78
3            8          85          78        76         80          82
4            9          88          80        80         84          86
5           10          90          84        82         86          90
6           11          92          86        85         88          93
7           12          95          90        88         92          97
8            5          75          70        68         72          71
9            6          80          72        70         75          74
10           7          82          75        74         78          78
11           8          85          78        76         80          82
12           9          88          80        80         84          86
13          10          90          84        82         86          90
14          11          92          86        85         88          93
15          12          95          90        88         92          97
16           5          75          70        68         72          71
17           6          80          72        70         75          74
18           7          82          75        74         78          78
19           8          85          78        76         80          82
20           9          88          80        80         84          86
21          10          90          84        82         86          90
22          11          92          86        85         88          93
23          12          95          90        88         92          97
24           5          75          70        68         72          71
25           6          80          72        70         75          74
26           7          82          75        74         78          78
27           8          85          78        76         80          82
28           9          88          80        80         84          86
29          10          90          84        82         86          90
30          11          92          86        85         88          93
31          12          95          90        88         92          97
32           5          75          70        68         72          71
33           6          80          72        70         75          74
34           7          82          75        74         78          78
35           8          85          78        76         80          82
36           9          88          80        80         84          86
37          10          90          84        82         86          90
38          11          92          86        85         88          93
39          12          95          90        88         92          97
40           5          75          70        68         72          71
41           6          80          72        70         75          74
42           7          82          75        74         78          78
43           8          85          78        76         80          82
44           9          88          80        80         84          86
45          10          90          84        82         86          90
46          11          92          86        85         88          93
47          12          95          90        88         92          97

In [29]:
df = pd.DataFrame(data)
df

    StudyHours  Attendance  Assignment  Internal  Practical  FinalMarks
0            5          75          70        68         72          71
1            6          80          72        70         75          74
2            7          82          75        74         78          78
3            8          85          78        76         80          82
4            9          88          80        80         84          86
5           10          90          84        82         86          90
6           11          92          86        85         88          93
7           12          95          90        88         92          97
8            5          75          70        68         72          71
9            6          80          72        70         75          74
10           7          82          75        74         78          78
11           8          85          78        76         80          82
12           9          88          80        80         84          86
13          10          90          84        82         86          90
14          11          92          86        85         88          93
15          12          95          90        88         92          97
16           5          75          70        68         72          71
17           6          80          72        70         75          74
18           7          82          75        74         78          78
19           8          85          78        76         80          82
20           9          88          80        80         84          86
21          10          90          84        82         86          90
22          11          92          86        85         88          93
23          12          95          90        88         92          97
24           5          75          70        68         72          71
25           6          80          72        70         75          74
26           7          82          75        74         78          78
27           8          85          78        76         80          82
28           9          88          80        80         84          86
29          10          90          84        82         86          90
30          11          92          86        85         88          93
31          12          95          90        88         92          97
32           5          75          70        68         72          71
33           6          80          72        70         75          74
34           7          82          75        74         78          78
35           8          85          78        76         80          82
36           9          88          80        80         84          86
37          10          90          84        82         86          90
38          11          92          86        85         88          93
39          12          95          90        88         92          97
40           5          75          70        68         72          71
41           6          80          72        70         75          74
42           7          82          75        74         78          78
43           8          85          78        76         80          82
44           9          88          80        80         84          86
45          10          90          84        82         86          90
46          11          92          86        85         88          93
47          12          95          90        88         92          97

In [32]:
# Independent variables
X = df.iloc[:,:-1]
# Dependent variable
Y = df['FinalMarks']
print(X)
print(Y)

    StudyHours  Attendance  Assignment  Internal  Practical
0            5          75          70        68         72
1            6          80          72        70         75
2            7          82          75        74         78
3            8          85          78        76         80
4            9          88          80        80         84
5           10          90          84        82         86
6           11          92          86        85         88
7           12          95          90        88         92
8            5          75          70        68         72
9            6          80          72        70         75
10           7          82          75        74         78
11           8          85          78        76         80
12           9          88          80        80         84
13          10          90          84        82         86
14          11          92          86        85         88
15          12          95          90        88         92
16           5          75          70        68         72
17           6          80          72        70         75
18           7          82          75        74         78
19           8          85          78        76         80
20           9          88          80        80         84
21          10          90          84        82         86
22          11          92          86        85         88
23          12          95          90        88         92
24           5          75          70        68         72
25           6          80          72        70         75
26           7          82          75        74         78
27           8          85          78        76         80
28           9          88          80        80         84
29          10          90          84        82         86
30          11          92          86        85         88
31          12          95          90        88         92
32           5          75          70        68         72
33           6          80          72        70         75
34           7          82          75        74         78
35           8          85          78        76         80
36           9          88          80        80         84
37          10          90          84        82         86
38          11          92          86        85         88
39          12          95          90        88         92
40           5          75          70        68         72
41           6          80          72        70         75
42           7          82          75        74         78
43           8          85          78        76         80
44           9          88          80        80         84
45          10          90          84        82         86
46          11          92          86        85         88
47          12          95          90        88         92
0     71
1     74
2     78
3     82
4     86
5     90
6     93
7     97
8     71
9     74
10    78
11    82
12    86
13    90
14    93
15    97
16    71
17    74
18    78
19    82
20    86
21    90
22    93
23    97
24    71
25    74
26    78
27    82
28    86
29    90
30    93
31    97
32    71
33    74
34    78
35    82
36    86
37    90
38    93
39    97
40    71
41    74
42    78
43    82
44    86
45    90
46    93
47    97
Name: FinalMarks, dtype: int64

In [34]:
# Split data
X_train,X_test,Y_train,Y_test = train_test_split(
    X,Y,test_size=0.3,random_state=80)
print(X_test)
print(Y_train)

    StudyHours  Attendance  Assignment  Internal  Practical
20           9          88          80        80         84
41           6          80          72        70         75
34           7          82          75        74         78
42           7          82          75        74         78
26           7          82          75        74         78
44           9          88          80        80         84
21          10          90          84        82         86
27           8          85          78        76         80
39          12          95          90        88         92
11           8          85          78        76         80
13          10          90          84        82         86
1            6          80          72        70         75
31          12          95          90        88         92
12           9          88          80        80         84
6           11          92          86        85         88
30    93
36    86
32    71
18    78
16    71
2     78
45    90
33    74
43    82
29    90
24    71
37    90
46    93
7     97
40    71
8     71
25    74
14    93
35    82
4     86
28    86
9     74
0     71
5     90
17    74
15    97
23    97
22    93
3     82
10    78
19    82
38    93
47    97
Name: FinalMarks, dtype: int64

In [36]:
# Model
model = LinearRegression()
model.fit(X_train,Y_train)

# Intercept
print("Intercept:",model.intercept_)

# Coefficients
print("Coefficients:",model.coef_)

Intercept: -10.49038818377494
Coefficients: [ 0.50345135  0.23580494  0.55280932  0.67342092 -0.32338752]

In [40]:
# Prediction for new student
new_data = [[10,89,83,81,85]]
prediction = model.predict(X_test)

print("Predicted Final Marks =",prediction)

Predicted Final Marks = [85.72537668 74.082387   78.43939731 78.43939731 78.43939731 85.72537668
 89.611742   82.00875826 97.21472575 82.00875826 89.611742   74.082387
 97.21472575 85.72537668 93.0659096 ]